export class ClientEvents {
	static STATUS_CHANGED: "STATUS_CHANGED";
	static STATE_CHANGED: "STATE_CHANGED";
	static ANY_PDU: "ANY_PDU";
	static MESSAGE_SEND_COUNTER_UPDATE_EVENT: "MESSAGE_SEND_COUNTER_UPDATE_EVENT";
}